const dataListCon = [
        {
          "job_no": 007,
          "name": "Test project - Hamilton",
          "address": "-37.778409, 175.263883",
          "job_floor_area": 3000,
          "steel_detailing": "Yes",
          "total_weight": 200,
          "precast_detailing": "No",
          "panel_quantity": 0,
          "structural_drafting": "No",
          "consulting": "No",
          "image": "https://www.dropbox.com/s/cqsa4vih1tk98ff/20161206_153842.jpg?raw=1"
        },
        {
          "job_no": 008,
          "name": "Test project - Tauranga",
          "address": "-37.693277, 176.150226",
          "job_floor_area": 3000,
          "steel_detailing": "No",
          "total_weight": 200,
          "precast_detailing": "Yes",
          "panel_quantity": 0,
          "structural_drafting": "No",
          "consulting": "No",
          "image": "https://www.dropbox.com/s/0mtowucdtfm1t1s/DetailConnect_abb.png?raw=1"
        },
        {
          "job_no": 009,
          "name": "Test project - Rotorua",
          "address": "-38.141727, 176.309979",
          "job_floor_area": 3000,
          "steel_detailing": "No",
          "total_weight": 200,
          "precast_detailing": "No",
          "panel_quantity": 0,
          "structural_drafting": "Yes",
          "consulting": "No",
          "image": "https://www.dropbox.com/s/0mtowucdtfm1t1s/DetailConnect_abb.png?raw=1"
        },
        {
          "job_no": 010,
          "name": "Test project - Te Kuiti",
          "address": "-38.324364, 175.162313",
          "job_floor_area": 3000,
          "steel_detailing": "No",
          "total_weight": 200,
          "precast_detailing": "No",
          "panel_quantity": 0,
          "structural_drafting": "No",
          "consulting": "Yes",
          "image": "https://www.dropbox.com/s/0mtowucdtfm1t1s/DetailConnect_abb.png?raw=1"
        },
        {
          "job_no": 011,
          "name": "Test project - Whangarei",
          "address": " -35.724093, 174.315189",
          "job_floor_area": 3000,
          "steel_detailing": "Yes",
          "total_weight": 200,
          "precast_detailing": "No",
          "panel_quantity": 0,
          "structural_drafting": "Yes",
          "consulting": "No",
          "image": "https://www.dropbox.com/s/0mtowucdtfm1t1s/DetailConnect_abb.png?raw=1"
        }
        // {
        //   "job_no": 12024,
        //   "name": "Home Of Cycling - Amenities",
        //   "address": "-37.8896326,175.4339056",
        //   "job_floor_area": 3000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 200,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "Yes"
        // },
        // {
        //   "job_no": 13020,
        //   "name": "Bunnings New Lynn",
        //   "address": "-36.909742, 174.677840",
        //   "job_floor_area": 12000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 345,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 13046,
        //   "name": "APL - Hamilton",
        //   "address": "-37.748441, 175.238546",
        //   "job_floor_area": 6000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 216,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 14000,
        //   "name": "254 Montreal Street Christchurch",
        //   "address": "-43.533448, 172.630762",
        //   "job_floor_area": 3800,
        //   "steel_detailing": "Yes",
        //   "total_weight": 215,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15018,
        //   "name": "Pellet Tower",
        //   "address": "-44.4507735,171.0937536",
        //   "job_floor_area": 380,
        //   "steel_detailing": "Yes",
        //   "total_weight": 27,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15024,
        //   "name": "11 Maurice WIlson Ave",
        //   "address": "-36.9901295,174.7782366",
        //   "job_floor_area": 12000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 432,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15034,
        //   "name": "Tegal",
        //   "address": "-39.0555364,174.2077624",
        //   "job_floor_area": 1620,
        //   "steel_detailing": "Yes",
        //   "total_weight": 61.5,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15040,
        //   "name": "Project 56 Lift & Stairs",
        //   "address": "-41.2808132,174.7726907",
        //   "job_floor_area": 100,
        //   "steel_detailing": "Yes",
        //   "total_weight": 3.7,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15055,
        //   "name": "Omokoroa - Freshchoice",
        //   "address": "-37.6418275,176.0362281",
        //   "job_floor_area": 1936,
        //   "steel_detailing": "Yes",
        //   "total_weight": 57,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15061,
        //   "name": "338 Stafford Street",
        //   "address": "-44.3931156,171.2472691",
        //   "job_floor_area": 1250,
        //   "steel_detailing": "Yes",
        //   "total_weight": 12.1,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15065,
        //   "name": "Bledisloe Sports Pavillion",
        //   "address": "-37.2076318,174.898491",
        //   "job_floor_area": 500,
        //   "steel_detailing": "Yes",
        //   "total_weight": 20,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15067,
        //   "name": "Asmuss Warehouse",
        //   "address": "-39.039071,174.1615944",
        //   "job_floor_area": 1413,
        //   "steel_detailing": "Yes",
        //   "total_weight": 65,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15069,
        //   "name": "209 Marine Parade",
        //   "address": "-37.653950, 176.207101",
        //   "job_floor_area": 1200,
        //   "steel_detailing": "Yes",
        //   "total_weight": 25,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15077,
        //   "name": "St Johns College",
        //   "address": "-39.6409197,176.8550582",
        //   "job_floor_area": 1023,
        //   "steel_detailing": "Yes",
        //   "total_weight": 31.4,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15078,
        //   "name": "18 St Martin Lane",
        //   "address": "-36.8584136,174.7631106",
        //   "job_floor_area": 1600,
        //   "steel_detailing": "Yes",
        //   "total_weight": 70,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "Yes",
        //   "consulting": "Yes"
        // },
        // {
        //   "job_no": 15083,
        //   "name": "Coombes BMW",
        //   "address": "-37.7585412,175.2439379",
        //   "job_floor_area": 3250,
        //   "steel_detailing": "Yes",
        //   "total_weight": 52,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15090,
        //   "name": "St Josephs School",
        //   "address": "-38.0025089,177.2835785",
        //   "job_floor_area": 730,
        //   "steel_detailing": "Yes",
        //   "total_weight": 8.5,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15095,
        //   "name": "Bethlehem School",
        //   "address": "-37.690473,176.105877",
        //   "job_floor_area": 750,
        //   "steel_detailing": "Yes",
        //   "total_weight": 16,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15101,
        //   "name": "Apata Coolstore",
        //   "address": "-37.6522005,175.9832892",
        //   "job_floor_area": 7000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 214,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 15102,
        //   "name": "Papamoa Plaza",
        //   "address": "-37.6988311,176.2809586",
        //   "job_floor_area": 2700,
        //   "steel_detailing": "Yes",
        //   "total_weight": 121,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16000,
        //   "name": "Maketu Hauora",
        //   "address": "-37.7589015,176.4500527",
        //   "job_floor_area": 408.3,
        //   "steel_detailing": "Yes",
        //   "total_weight": 5.5,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16004,
        //   "name": "Lake Hayes Residential",
        //   "address": "-44.9900217,168.8130544",
        //   "job_floor_area": 1100,
        //   "steel_detailing": "Yes",
        //   "total_weight": 23.8,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16012,
        //   "name": "Kennards Hire Te Rapa",
        //   "address": "-37.7544115,175.2393135",
        //   "job_floor_area": 520,
        //   "steel_detailing": "Yes",
        //   "total_weight": 20,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16015,
        //   "name": "Lakes Boulevard",
        //   "address": "-37.7504796,176.104847517",
        //   "job_floor_area": 1000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 28,
        //   "precast_detailing": "Yes",
        //   "panel_quantity": 32,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16027,
        //   "name": "Countdown Aotea",
        //   "address": "-41.1217829,174.8579875",
        //   "job_floor_area": 3135,
        //   "steel_detailing": "Yes",
        //   "total_weight": 124,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16030,
        //   "name": "Countdown Mosgiel",
        //   "address": "-45.880446, 170.351851",
        //   "job_floor_area": 4300,
        //   "steel_detailing": "Yes",
        //   "total_weight": 120,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16031,
        //   "name": "Tauranga Intermediate",
        //   "address": "-37.7121319,176.1536352",
        //   "job_floor_area": 1500,
        //   "steel_detailing": "Yes",
        //   "total_weight": 26,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16032,
        //   "name": "Northbridge Apartments",
        //   "address": "-36.796742, 174.754044",
        //   "job_floor_area": 7488,
        //   "steel_detailing": "Yes",
        //   "total_weight": 38.6,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16033,
        //   "name": "Rakaia Seeds",
        //   "address": "-43.674081, 171.851686",
        //   "job_floor_area": 1000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 18,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16034,
        //   "name": "Kiwi Bus Builders",
        //   "address": "-37.7444882,176.0947835",
        //   "job_floor_area": 2265,
        //   "steel_detailing": "Yes",
        //   "total_weight": 68,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16038,
        //   "name": "Vulcan Steel Invercargill",
        //   "address": "-46.416416, 168.340409",
        //   "job_floor_area": 1200,
        //   "steel_detailing": "Yes",
        //   "total_weight": 42,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16039,
        //   "name": "Mount Central",
        //   "address": "-37.639957, 176.184452",
        //   "job_floor_area": 1380,
        //   "steel_detailing": "Yes",
        //   "total_weight": 70,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16040,
        //   "name": "Port A Shed Extension",
        //   "address": "-45.8149509,170.6206233",
        //   "job_floor_area": 1444,
        //   "steel_detailing": "Yes",
        //   "total_weight": 24,
        //   "precast_detailing": "Yes",
        //   "panel_quantity": 34,
        //   "structural_drafting": "Yes",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16042,
        //   "name": "1343 Cameron Rd",
        //   "address": "-37.7266818,176.1299681",
        //   "job_floor_area": 400,
        //   "steel_detailing": "Yes",
        //   "total_weight": 6.9,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16043,
        //   "name": "Redmond Shed",
        //   "address": "-43.9121648,171.951746",
        //   "job_floor_area": 1000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 20,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16044,
        //   "name": "Pan Pac",
        //   "address": "-46.075876, 170.004486",
        //   "job_floor_area": 4800,
        //   "steel_detailing": "Yes",
        //   "total_weight": 100,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16046,
        //   "name": "Swim School Aquatic Centre",
        //   "address": "-37.7705388,176.0953012",
        //   "job_floor_area": 1155,
        //   "steel_detailing": "Yes",
        //   "total_weight": 13.8,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16056,
        //   "name": "Tauriko Trade Units",
        //   "address": "-37.7345618,176.0809773",
        //   "job_floor_area": 2000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 45,
        //   "precast_detailing": "Yes",
        //   "panel_quantity": 93,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16060,
        //   "name": "Keys Residence",
        //   "address": "-37.740236,176.107237",
        //   "job_floor_area": 300,
        //   "steel_detailing": "Yes",
        //   "total_weight": 1.34,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16062,
        //   "name": "Otumoetai College",
        //   "address": "-37.6798611,176.1272519",
        //   "job_floor_area": 1200,
        //   "steel_detailing": "Yes",
        //   "total_weight": 8,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16064,
        //   "name": "Hamilton City Reservoir",
        //   "address": "-37.7111209,175.256478",
        //   "job_floor_area": 3800,
        //   "steel_detailing": "No",
        //   "total_weight": 0,
        //   "precast_detailing": "Yes",
        //   "panel_quantity": 116,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16066,
        //   "name": "Port Nelson",
        //   "address": "-41.2633492,173.2745168",
        //   "job_floor_area": 16000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 494,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "Yes",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16069,
        //   "name": "Marina Villas",
        //   "address": "-37.0005327,175.8498939",
        //   "job_floor_area": 1100,
        //   "steel_detailing": "Yes",
        //   "total_weight": 13.75,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16070,
        //   "name": "McFall Residence",
        //   "address": "-38.1104986,175.3500083",
        //   "job_floor_area": 400,
        //   "steel_detailing": "Yes",
        //   "total_weight": 2,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16072,
        //   "name": "90 Whakakake Street",
        //   "address": "-37.7425838,176.0953605",
        //   "job_floor_area": 2000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 16.77,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16074,
        //   "name": "202 Hastings Street",
        //   "address": "-39.491572, 176.918600",
        //   "job_floor_area": 2000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 86,
        //   "precast_detailing": "Yes",
        //   "panel_quantity": 49,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16075,
        //   "name": "Bombay Fuel Canopy",
        //   "address": "-37.0878193,174.9376282",
        //   "job_floor_area": 312,
        //   "steel_detailing": "Yes",
        //   "total_weight": 9.8,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "Yes",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16076,
        //   "name": "94 Bryce St Precast",
        //   "address": "-37.7865346,175.2742873",
        //   "job_floor_area": 3000,
        //   "steel_detailing": "No",
        //   "total_weight": 147,
        //   "precast_detailing": "Yes",
        //   "panel_quantity": 29,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16079,
        //   "name": "5 Rathbone Street",
        //   "address": "-35.724715, 174.320507",
        //   "job_floor_area": 810,
        //   "steel_detailing": "Yes",
        //   "total_weight": 28,
        //   "precast_detailing": "Yes",
        //   "panel_quantity": 30,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16080,
        //   "name": "39 Aerodrome Road",
        //   "address": "-37.6662342,176.2012262",
        //   "job_floor_area": 430,
        //   "steel_detailing": "Yes",
        //   "total_weight": 8.1,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16081,
        //   "name": "Opac Coolstores",
        //   "address": "-38.024947,177.2874013",
        //   "job_floor_area": 7800,
        //   "steel_detailing": "Yes",
        //   "total_weight": 60,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16084,
        //   "name": "Tekapo Four Square",
        //   "address": "-44.0414093,170.4331509",
        //   "job_floor_area": 1232,
        //   "steel_detailing": "Yes",
        //   "total_weight": 25,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16085,
        //   "name": "Riverhead Development",
        //   "address": "-36.7564496,174.5897563",
        //   "job_floor_area": 600,
        //   "steel_detailing": "Yes",
        //   "total_weight": 25.5,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16088,
        //   "name": "Allenton Medical Centre",
        //   "address": "-43.8891108,171.7359253",
        //   "job_floor_area": 962,
        //   "steel_detailing": "Yes",
        //   "total_weight": 19.34,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16090,
        //   "name": "Stokes Valley CC",
        //   "address": "-40.673314,175.149866",
        //   "job_floor_area": 982,
        //   "steel_detailing": "Yes",
        //   "total_weight": 54,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16095,
        //   "name": "Bombay Canopy",
        //   "address": "-37.1615124,174.9805915",
        //   "job_floor_area": 304,
        //   "steel_detailing": "Yes",
        //   "total_weight": 9.8,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "Yes",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16098,
        //   "name": "Niagara 34m Span",
        //   "address": "-43.8897107,171.7322407",
        //   "job_floor_area": 5500,
        //   "steel_detailing": "Yes",
        //   "total_weight": 110.85,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16099,
        //   "name": "St Johns Tauranga",
        //   "address": "-37.705708, 176.149405",
        //   "job_floor_area": 1680,
        //   "steel_detailing": "Yes",
        //   "total_weight": 50,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 16102,
        //   "name": "Egmont Seeds",
        //   "address": "-39.098341,174.0566332",
        //   "job_floor_area": 360,
        //   "steel_detailing": "Yes",
        //   "total_weight": 11,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 17002,
        //   "name": "Van Assalt",
        //   "address": "-37.9527911,176.9628708",
        //   "job_floor_area": 540,
        //   "steel_detailing": "Yes",
        //   "total_weight": 5.32,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 17003,
        //   "name": "Pilot Bay Apartments",
        //   "address": "-37.636067, 176.179313",
        //   "job_floor_area": 2000,
        //   "steel_detailing": "Yes",
        //   "total_weight": 26.84,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 17005,
        //   "name": "Pukaki Airfield",
        //   "address": "-44.2341003,170.1148993",
        //   "job_floor_area": 420,
        //   "steel_detailing": "Yes",
        //   "total_weight": 16.69,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 17006,
        //   "name": "Meteor Theatre",
        //   "address": "-37.7922088,175.2851954",
        //   "job_floor_area": 1400,
        //   "steel_detailing": "Yes",
        //   "total_weight": 12.65,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 17008,
        //   "name": "Mainland Coachworks",
        //   "address": "-43.8808322,171.792978",
        //   "job_floor_area": 930,
        //   "steel_detailing": "Yes",
        //   "total_weight": 21.9,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // },
        // {
        //   "job_no": 17014,
        //   "name": "Bloom Childcare",
        //   "address": "-37.7166042,176.3060166",
        //   "job_floor_area": 900,
        //   "steel_detailing": "Yes",
        //   "total_weight": 25,
        //   "precast_detailing": "No",
        //   "panel_quantity": 0,
        //   "structural_drafting": "No",
        //   "consulting": "No"
        // }
      ]
  // }

const dataObj = Object.values(dataListCon);
console.log(dataObj);
console.log(dataObj[0].steel_detailing);