function dataList() {
    return [
    // new postObject(1,
    // "Tauranga Intermediate",
    // ["service1", "service2", "service3"],
    // "18 (T)","1000 (m2)",
    // "http://www.detailc.moodsdigital.biz/wp-content/uploads/2017\/04/Aerial-Site-Photo-1.jpeg",
    // ["-37.7119016", "176.15580449999993", "10"]),
        {
            "ID": 2,
            "post_title": "Tauranga Intermediate 2",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "tauranga-intermediate",
            "guid": "http:\/\/www.detailc.moodsdigital.biz\/?post_type=map-location&#038;p=116757",
            "google_coords": ["-40.4447024", "175.8213945", "10"],
            "pin_image": { "url": "", "size": false, "anchor": [0, 0] },
            "data_tags": { "14": 14 },
            "services": ["service1"],
            "total_weight": "18 (T)",
            "floor_area": "1000 (m2)",
            "project_image": "https://www.detailconnect.nz/wp-content/uploads/2017/04/Aerial-Site-Photo-1.jpeg",
            "tooltip_content": "<p><strong>Tauranga Intermediate<\/strong><br \/><img src=\"http:\/\/www.detailc.moodsdigital.biz\/wp-content\/uploads\/2017\/04\/Aerial-Site-Photo-1.jpeg\"><\/p>\n<p><strong>Services<\/strong><\/p>\n<p><input type=\"checkbox\" checked=\"checked\"><\/input><label>Precast<\/label><br \/>\n<strong>Total Weight:<\/strong> 26 (T)<br \/>\n<strong>Job Floor Area:<\/strong> 1500 (m2)<\/p>\n"
        },
        {
            "ID": 3,
            "post_title": "Tauranga Intermediate 3",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "tauranga-intermediate",
            "guid": "http:\/\/www.detailc.moodsdigital.biz\/?post_type=map-location&#038;p=116757",
            "google_coords": ["-41.280562", "174.77490280000006", "10"],
            "pin_image": { "url": "", "size": false, "anchor": [0, 0] },
            "data_tags": { "14": 14 },
            "services": ["service1", "service3"],
            "total_weight": "18 (T)",
            "floor_area": '',
            "project_image": "https://www.detailconnect.nz/wp-content/uploads/2017/04/Aerial-Site-Photo-1.jpeg",
            "tooltip_content": "<p><strong>Tauranga Intermediate<\/strong><br \/><img src=\"http:\/\/www.detailc.moodsdigital.biz\/wp-content\/uploads\/2017\/04\/Aerial-Site-Photo-1.jpeg\"><\/p>\n<p><strong>Services<\/strong><\/p>\n<p><input type=\"checkbox\" checked=\"checked\"><\/input><label>Precast<\/label><br \/>\n<strong>Total Weight:<\/strong> 26 (T)<br \/>\n<strong>Job Floor Area:<\/strong> 1500 (m2)<\/p>\n"
        },
        {
            "ID": 4,
            "post_title": "Testing",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "tauranga-intermediate",
            "guid": "http:\/\/www.detailc.moodsdigital.biz\/?post_type=map-location&#038;p=116757",
            "google_coords": ["-41.280562", "174.77490280000006", "10"],
            "pin_image": { "url": "", "size": false, "anchor": [0, 0] },
            "data_tags": { "14": 14 },
            "services": ["service1", "service3"],
            "total_weight": "18 (T)",
            "floor_area": '',
            "project_image": "https://www.detailconnect.nz/wp-content/uploads/2017/04/Aerial-Site-Photo-1.jpeg",
            "tooltip_content": "<p><strong>Tauranga Intermediate<\/strong><br \/><img src=\"http:\/\/www.detailc.moodsdigital.biz\/wp-content\/uploads\/2017\/04\/Aerial-Site-Photo-1.jpeg\"><\/p>\n<p><strong>Services<\/strong><\/p>\n<p><input type=\"checkbox\" checked=\"checked\"><\/input><label>Precast<\/label><br \/>\n<strong>Total Weight:<\/strong> 26 (T)<br \/>\n<strong>Job Floor Area:<\/strong> 1500 (m2)<\/p>\n"
        }
    ]
}